/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardPlanBuilderRouteImport } from './routes/dashboard.plan-builder'
import { Route as DashboardMonitorRouteImport } from './routes/dashboard.monitor'
import { Route as DashboardKnowledgeBaseRouteImport } from './routes/dashboard.knowledge-base'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard.compliance'
import { Route as DashboardChatRouteImport } from './routes/dashboard.chat'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanBuilderRoute = DashboardPlanBuilderRouteImport.update({
  id: '/plan-builder',
  path: '/plan-builder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitorRoute = DashboardMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKnowledgeBaseRoute = DashboardKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/knowledge-base': typeof DashboardKnowledgeBaseRoute
  '/dashboard/monitor': typeof DashboardMonitorRoute
  '/dashboard/plan-builder': typeof DashboardPlanBuilderRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/knowledge-base': typeof DashboardKnowledgeBaseRoute
  '/dashboard/monitor': typeof DashboardMonitorRoute
  '/dashboard/plan-builder': typeof DashboardPlanBuilderRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/knowledge-base': typeof DashboardKnowledgeBaseRoute
  '/dashboard/monitor': typeof DashboardMonitorRoute
  '/dashboard/plan-builder': typeof DashboardPlanBuilderRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/chat'
    | '/dashboard/compliance'
    | '/dashboard/knowledge-base'
    | '/dashboard/monitor'
    | '/dashboard/plan-builder'
    | '/dashboard/reports'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/chat'
    | '/dashboard/compliance'
    | '/dashboard/knowledge-base'
    | '/dashboard/monitor'
    | '/dashboard/plan-builder'
    | '/dashboard/reports'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/chat'
    | '/dashboard/compliance'
    | '/dashboard/knowledge-base'
    | '/dashboard/monitor'
    | '/dashboard/plan-builder'
    | '/dashboard/reports'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plan-builder': {
      id: '/dashboard/plan-builder'
      path: '/plan-builder'
      fullPath: '/dashboard/plan-builder'
      preLoaderRoute: typeof DashboardPlanBuilderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitor': {
      id: '/dashboard/monitor'
      path: '/monitor'
      fullPath: '/dashboard/monitor'
      preLoaderRoute: typeof DashboardMonitorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/knowledge-base': {
      id: '/dashboard/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/dashboard/knowledge-base'
      preLoaderRoute: typeof DashboardKnowledgeBaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardKnowledgeBaseRoute: typeof DashboardKnowledgeBaseRoute
  DashboardMonitorRoute: typeof DashboardMonitorRoute
  DashboardPlanBuilderRoute: typeof DashboardPlanBuilderRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatRoute: DashboardChatRoute,
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardKnowledgeBaseRoute: DashboardKnowledgeBaseRoute,
  DashboardMonitorRoute: DashboardMonitorRoute,
  DashboardPlanBuilderRoute: DashboardPlanBuilderRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
