"""Tests for the PDF report generator."""
from __future__ import annotations

import pytest
from unittest.mock import MagicMock


def _make_full_state() -> dict:
    """Create a complete mock HACCP plan state for PDF generation."""
    return {
        "plan_id": "test-plan-pdf-001",
        "business_name": "Sunrise Dairy Processing Pvt. Ltd.",
        "product_category": "dairy_pasteurized",
        "process_steps": [
            "Raw Milk Reception",
            "Filtration",
            "Standardisation",
            "Pasteurisation",
            "Homogenisation",
            "Packaging",
            "Cold Storage",
            "Dispatch",
        ],
        "hazards_identified": [
            {
                "process_step": "Pasteurisation",
                "name": "Salmonella spp.",
                "category": "biological",
                "likelihood": 4,
                "severity": 5,
                "recommended_control": "Pasteurize at ≥72°C for 15 seconds per FSSAI Schedule 4",
            },
            {
                "process_step": "Raw Milk Reception",
                "name": "Antibiotic residues (penicillin, tetracycline)",
                "category": "chemical",
                "likelihood": 3,
                "severity": 4,
                "recommended_control": "Antibiotic screening of every tanker — reject if positive",
            },
            {
                "process_step": "Packaging",
                "name": "Glass fragments from broken packaging",
                "category": "physical",
                "likelihood": 2,
                "severity": 3,
                "recommended_control": "Line inspection and packaging material integrity checks",
            },
        ],
        "ccps_approved": [
            {
                "process_step": "Pasteurisation",
                "hazard_name": "Salmonella spp.",
                "decision_tree_path": ["Q1: Yes", "Q2: Yes → CCP"],
                "user_override": False,
            },
            {
                "process_step": "Raw Milk Reception",
                "hazard_name": "Antibiotic residues",
                "decision_tree_path": ["Q1: Yes", "Q2: Yes → CCP"],
                "user_override": True,
                "override_justification": "Mandatory per FSSAI dairy regulations",
            },
        ],
        "critical_limits": {
            "Pasteurisation - Salmonella spp.": {
                "parameter": "Temperature",
                "min_value": 72.0,
                "max_value": None,
                "unit": "°C",
                "source_citation": "FSSAI Schedule 4 Part I §6.3, ICMR Dairy Standards 2023",
                "user_validated": True,
            },
        },
        "monitoring_procedures": [
            {
                "ccp_hazard": "Pasteurisation - Salmonella spp.",
                "method": "Continuous temperature recording via calibrated digital thermometer",
                "frequency": "Continuous with chart recorder; manual verification every 30 minutes",
                "responsible_person": "Production Supervisor",
                "record_format": "CCP-01 Temperature Log",
            },
        ],
        "corrective_actions": [
            {
                "ccp_hazard": "Pasteurisation - Salmonella spp.",
                "trigger_condition": "Temperature drops below 72°C",
                "immediate_action": "Halt production, divert product to re-pasteurization or discard",
                "root_cause_procedure": "Investigate heat exchanger, check CIP cycle, recalibrate sensor",
                "personnel": "QA Manager + Production Supervisor",
            },
        ],
        "verification_schedule": {
            "internal_audit_frequency": "Monthly",
            "ccp_verification_frequency": "Weekly",
            "calibration_schedule": "All temperature sensors calibrated quarterly",
            "record_review": "QA Manager reviews all CCP logs weekly",
            "external_audit": "Annual FSSAI inspection + third-party audit",
        },
        "records_generated": [
            "CCP-01 Pasteurisation Temperature Log",
            "CA-01 Corrective Action Log",
            "VER-01 Verification Schedule",
        ],
    }


class TestPdfGenerator:
    """Tests for utils/pdf_generator.py."""

    def test_generates_pdf_bytes(self):
        """generate_haccp_pdf should return non-empty bytes."""
        from utils.pdf_generator import generate_haccp_pdf

        state = _make_full_state()
        pdf_bytes = generate_haccp_pdf(state)

        assert isinstance(pdf_bytes, bytes)
        assert len(pdf_bytes) > 5000  # PDF should be at least a few KB

    def test_pdf_starts_with_pdf_magic(self):
        """Generated bytes should start with PDF magic bytes %PDF."""
        from utils.pdf_generator import generate_haccp_pdf

        pdf_bytes = generate_haccp_pdf(_make_full_state())
        assert pdf_bytes[:4] == b"%PDF"

    def test_empty_state_does_not_crash(self):
        """generate_haccp_pdf should not crash on an empty state dict."""
        from utils.pdf_generator import generate_haccp_pdf

        pdf_bytes = generate_haccp_pdf({})
        assert isinstance(pdf_bytes, bytes)
        assert len(pdf_bytes) > 0

    def test_minimal_state(self):
        """generate_haccp_pdf should work with only business_name and product_category."""
        from utils.pdf_generator import generate_haccp_pdf

        state = {
            "plan_id": "test-minimal",
            "business_name": "Minimal Bakery",
            "product_category": "rte",
            "process_steps": ["Mixing", "Baking", "Packaging"],
            "hazards_identified": [],
            "ccps_approved": [],
            "critical_limits": {},
            "monitoring_procedures": [],
            "corrective_actions": [],
            "verification_schedule": {},
        }
        pdf_bytes = generate_haccp_pdf(state)
        assert isinstance(pdf_bytes, bytes)
        assert len(pdf_bytes) > 1000

    def test_no_ccps_section(self):
        """Should render correctly even with no CCPs defined."""
        from utils.pdf_generator import generate_haccp_pdf

        state = _make_full_state()
        state["ccps_approved"] = []
        state["critical_limits"] = {}
        pdf_bytes = generate_haccp_pdf(state)
        assert isinstance(pdf_bytes, bytes)

    def test_user_override_ccp_renders(self):
        """Plans with user-override CCPs should include override notation in PDF."""
        from utils.pdf_generator import generate_haccp_pdf

        state = _make_full_state()
        # Ensure the override CCP is present
        assert any(c["user_override"] for c in state["ccps_approved"])
        pdf_bytes = generate_haccp_pdf(state)
        assert isinstance(pdf_bytes, bytes)
        assert len(pdf_bytes) > 5000

    def test_large_hazard_list(self):
        """Should handle a large number of hazards without crashing."""
        from utils.pdf_generator import generate_haccp_pdf

        state = _make_full_state()
        # Add many hazards
        for i in range(20):
            state["hazards_identified"].append({
                "process_step": f"Step {i}",
                "name": f"Hazard {i}",
                "category": "biological",
                "likelihood": 3,
                "severity": 3,
                "recommended_control": f"Control measure {i}",
            })
        pdf_bytes = generate_haccp_pdf(state)
        assert isinstance(pdf_bytes, bytes)
        assert len(pdf_bytes) > 5000
